[package]
name = "berlioz"
version = "0.1.0"
edition = "2021"

[dependencies]
comemo = "0.3.1"
enum-ordinalize = "4.2.0"
logos = "0.13.0"
nom = "7.1.3"
rowan = "0.15.13"
rowan-nom = "0.1.0"

[build-dependencies]
case = "1.0.0"
ungrammar = "1.16.1"
